# **PROJECT OF DATA AND INFORMATION QUALITY 2024/25**

## **0.** Initialization

In [ ]:
!pip install ydata-profiling
!pip install recordlinkage

In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import recordlinkage
from recordlinkage.datasets import load_febrl1
import warnings
warnings.filterwarnings('ignore')

## **1.** Data Profiling and Data Quality Assessment

In [ ]:
url = "https://raw.githubusercontent.com/LeoLe12/DIQ---ProjectLeiMantegazza-24-25-/main/Comune-di-Milano---Attivita-commerciali-di-media-e-grande-distribuzione.csv"
DATA = pd.read_csv(url, encoding="unicode_escape", sep=";")
DATA

Settore Merceologico              Insegna  \
0                                          NaN                  NaN   
1                                          NaN                  NaN   
2                                          NaN                  NaN   
3                                          NaN                  NaN   
4                                          NaN                  NaN   
..                                         ...                  ...   
906  non alimentare;tabella speciale monopolio                  NaN   
907                tabella speciale carburanti                  NaN   
908                  tabella speciale farmacie             farmacia   
909                  tabella speciale farmacie  farmacia cassiodoro   
910                  tabella speciale farmacie     farmacia scevola   

                                            Ubicazione Tipo Via  \
0    PZA CORDUSIO N. 2 ;pza cordusio 002; isolato:4...      PZA   
1                   RIP DI PTA TICINESE N. 73 (z.d. 1)      RIP   
2               VIA ALBERICO DA ROSCIATE N. 5 (z.d. 7)      VIA   
3    VIA ASTESANI ALESSANDRO N. 17 ; isolato:100; a...      VIA   
4              VIA MONTE NAPOLEONE num.006/a; (z.d. 1)      VIA   
..                                                 ...      ...   
906  VIA MACCHI MAURO N. 42 ; isolato:031; accesso:...      VIA   
907  VIA GALLARATE N. 40 centro strada; isolato:228...      VIA   
908  ff porta g codvia 9403 num.000 ; isolato:259; ...      VIA   
909  VLE CASSIODORO N. 12 ; isolato:151; accesso: a...      VLE   
910  VLE TESTI FULVIO N. 90 ; isolato:145; accesso:...      VLE   

                      Via  Civico  Codice Via  ZD  Superficie vendita  \
0                CORDUSIO     2.0         626   1                 292   
1         DI PTA TICINESE    73.0        5150   6                 800   
2    ALBERICO DA ROSCIATE     5.0        6589   7                 726   
3     ASTESANI ALESSANDRO    17.0        1558   9                 370   
4         MONTE NAPOLEONE     NaN         219   1                 270   
..                    ...     ...         ...  ..                 ...   
906          MACCHI MAURO    42.0        2133   2                 350   
907             GALLARATE    40.0        7420   8                 800   
908      MAFFUCCI ANGIOLO    40.0        1276   9                 462   
909            CASSIODORO    12.0        6359   8                 591   
910          TESTI FULVIO    90.0        1441   9                 397   

     Superficie altri usi  Superficie totale  
0                     NaN                292  
1                     NaN                800  
2                     NaN                  0  
3                     NaN                370  
4                     NaN                270  
..                    ...                ...  
906                 475.0                825  
907                 100.0                900  
908                   NaN                753  
909                   NaN                776  
910                   NaN                624  

[911 rows x 11 columns]

In [ ]:
DATA["Settore Merceologico"].value_counts()

Settore Merceologico
non alimentare                                605
alimentare;non alimentare                     281
alimentare                                      4
non alimentare;tabella speciale carburanti      3
tabella speciale farmacie                       3
non alimentare;tabella speciale monopolio       2
tabella speciale carburanti                     1
Name: count, dtype: int64

In [ ]:
print(DATA.shape)
COLUMNS = DATA.columns
print(COLUMNS)


(911, 11)
Index(['Settore Merceologico', 'Insegna', 'Ubicazione', 'Tipo Via', 'Via',
       'Civico', 'Codice Via', 'ZD', 'Superficie vendita',
       'Superficie altri usi', 'Superficie totale'],
      dtype='object')


In [ ]:
DATA.describe()

Civico   Codice Via          ZD  Superficie vendita  \
count  839.000000   911.000000  911.000000          911.000000   
mean    31.625745  3295.103183    4.272228          824.916575   
std     46.591154  2519.929641    2.897609         1152.373253   
min      1.000000     1.000000    1.000000          251.000000   
25%      6.000000  1057.500000    1.000000          350.000000   
50%     15.000000  2424.000000    4.000000          500.000000   
75%     36.000000  5355.000000    7.000000          894.500000   
max    312.000000  7587.000000    9.000000        20340.000000   

       Superficie altri usi  Superficie totale  
count            155.000000         911.000000  
mean             359.638710        1173.396268  
std              586.329291        1682.936833  
min                1.000000           0.000000  
25%               50.000000         393.500000  
50%              150.000000         610.000000  
75%              370.000000        1271.500000  
max             4600.000000       20340.000000

In [ ]:
NUM = list(DATA.select_dtypes(include=['int64','float64']).columns)
DATA_NUM = DATA[NUM]
DATA_NUM.corr(method ='pearson')

Civico  Codice Via        ZD  Superficie vendita  \
Civico                1.000000    0.109151  0.180902            0.082241   
Codice Via            0.109151    1.000000  0.622076            0.063512   
ZD                    0.180902    0.622076  1.000000            0.070599   
Superficie vendita    0.082241    0.063512  0.070599            1.000000   
Superficie altri usi  0.062640    0.047396  0.138072            0.427509   
Superficie totale     0.098647    0.119070  0.127308            0.842968   

                      Superficie altri usi  Superficie totale  
Civico                            0.062640           0.098647  
Codice Via                        0.047396           0.119070  
ZD                                0.138072           0.127308  
Superficie vendita                0.427509           0.842968  
Superficie altri usi              1.000000           0.792681  
Superficie totale                 0.792681           1.000000

In [ ]:
#Thanks to ydata profiling library we can easily profile our dataset and extract quality assessment
PROFILE = ProfileReport(DATA)
PROFILE.to_file("PROFILE.html")
PROFILE

Output hidden; open in https://colab.research.google.com to view.

### DQ Assestment

In [ ]:
for col in DATA.columns:
    print("DQ Assessment for "+col+":")

    DISTINCT = (DATA[col].nunique())
    COUNT = DATA[col].count()
    ROWS = len(DATA[col])
    UNIQUENESS = DISTINCT / ROWS
    print("UNIQUENESS: ", UNIQUENESS)

    DISTINCTNESS = DISTINCT / COUNT
    print("DISTINCTNESS: ", DISTINCTNESS)

    MAX_COUNTS = max(DATA[col].value_counts())
    CONSTANCY = MAX_COUNTS / COUNT
    print("CONSTANCY: ", CONSTANCY)


    NULL = DATA[col].isnull().sum()
    NOT_NULL = ROWS - NULL
    COMPLETENESS = NOT_NULL / ROWS
    print("COMPLETENESS: ", COMPLETENESS)

    print("\n\n")

DQ Assessment for Settore Merceologico:
UNIQUENESS:  0.007683863885839737
DISTINCTNESS:  0.00778642936596218
CONSTANCY:  0.6729699666295884
COMPLETENESS:  0.986827661909989



DQ Assessment for Insegna:
UNIQUENESS:  0.40175631174533477
DISTINCTNESS:  0.6524064171122995
CONSTANCY:  0.053475935828877004
COMPLETENESS:  0.6158068057080132



DQ Assessment for Ubicazione:
UNIQUENESS:  0.9538968166849616
DISTINCTNESS:  0.9538968166849616
CONSTANCY:  0.0043907793633369925
COMPLETENESS:  1.0



DQ Assessment for Tipo Via:
UNIQUENESS:  0.015367727771679473
DISTINCTNESS:  0.015367727771679473
CONSTANCY:  0.6520307354555434
COMPLETENESS:  1.0



DQ Assessment for Via:
UNIQUENESS:  0.5433589462129528
DISTINCTNESS:  0.5433589462129528
CONSTANCY:  0.02854006586169045
COMPLETENESS:  1.0



DQ Assessment for Civico:
UNIQUENESS:  0.132821075740944
DISTINCTNESS:  0.14421930870083433
CONSTANCY:  0.08343265792610251
COMPLETENESS:  0.9209659714599341



DQ Assessment for Codice Via:
UNIQUENESS:  0.54994511

*COMPLETENESS*<br>
- Settore Merceologico: only 1.3% missing values, they can be imputed using simple technique.
- Superficie vendita: 0 missing values
- Superficie altri usi: 83% missing values, they can be computed easily from the other two attributes<br>
(Superficie altri usi = Superficie totale - Superficie vendita)
- Superficie totale: There are no missing values; however, 7 data samples have a value of 0 for this attribute, which is equivalent to a missing value.


- TOTAL COMPLETENESS OF DATASET: TODO

*CONSISTENCY ANALYSIS*
- Superficie vendita: should be <= of Superficie totale and > 0
- Superficie altri usi: should be <= than Superficie totale and >= 0
- Superficie totale: should be == to Superficie vendita + superficie altri usi, and > 0

In [ ]:
#Let's verify integrity rules
TOT_ROWS = DATA.shape[0]

#Superficie vendita
CONSISTENT_ROWS = (DATA['Superficie vendita'] > 0) & (DATA['Superficie vendita'] <= DATA['Superficie totale'])

print('Consistent rows for Superficie vendita: ' + str(CONSISTENT_ROWS.sum()) + ' - ' + str(int(CONSISTENT_ROWS.sum()/TOT_ROWS*100)) + '%')

#Show unconsistent rows
DATA[~CONSISTENT_ROWS][['Superficie vendita', 'Superficie totale']]


Consistent rows for Superficie vendita: 903 - 99%


Superficie vendita  Superficie totale
2                   726                  0
19                  536                 54
217                 765                  0
351                 700                  0
372                 310                  0
386                 300                  0
564                 388                  0
626                 386                  0

Consideration: some rows has 0 as 'Superficie totale', only one samples actually break the consistency rules with a 'Superficie totale' > 0

In [ ]:
#Superficie altri usi
CONSISTENT_ROWS = (DATA['Superficie altri usi'] >= 0.0) & (DATA['Superficie altri usi'] <= (DATA['Superficie totale']))
print('Consistent rows for Superficie altri usi: ' + str(CONSISTENT_ROWS.sum()) + ' - ' + str(int(CONSISTENT_ROWS.sum()/TOT_ROWS*100)) + '%')

#Show unconsisten rows (only superficie attributes)
DATA[~CONSISTENT_ROWS][['Superficie altri usi', 'Superficie totale']]

Consistent rows for Superficie altri usi: 154 - 16%


Superficie altri usi  Superficie totale
0                     NaN                292
1                     NaN                800
2                     NaN                  0
3                     NaN                370
4                     NaN                270
..                    ...                ...
904                   NaN                380
905                   NaN                601
908                   NaN                753
909                   NaN                776
910                   NaN                624

[757 rows x 2 columns]

Consideration: Clearly, most of the rows contain null values and therefore fail the integrity check. Let's temporarily remove them to focus only on the valid ones.

In [ ]:
#keep only non null rows on 'Superficie altri usi'
ROWS = DATA[DATA['Superficie altri usi'].notna()]
ROWS_COUNT = ROWS.shape[0]

CONSISTENT_ROWS = (ROWS['Superficie altri usi'] > 0) & (ROWS['Superficie altri usi'] <= (ROWS['Superficie totale']))
print('Consistent rows for Superficie altri usi (only notna rows): ' + str(CONSISTENT_ROWS.sum()) + ' - ' + str(int(CONSISTENT_ROWS.sum()/ROWS_COUNT*100)) + '%')
ROWS[~CONSISTENT_ROWS][['Superficie altri usi', 'Superficie totale']]


Consistent rows for Superficie altri usi (only notna rows): 154 - 99%


Superficie altri usi  Superficie totale
386                 291.0                  0

Consideration: only one rows among the valid ones is violating the constraint (but it's due the fact that 'Superficie totale' is 0 which is not a valid value)

In [ ]:
#Superficie totale
CONSISTENT_ROWS = (DATA['Superficie totale'] > 0) & (DATA['Superficie totale'] == (DATA['Superficie vendita'] + DATA['Superficie altri usi']))
print('Consistent rows for Superficie totale: ' + str(CONSISTENT_ROWS.sum()) + ' - ' + str(int(CONSISTENT_ROWS.sum()/TOT_ROWS*100)) + '%')
DATA[~CONSISTENT_ROWS][['Superficie vendita', 'Superficie altri usi', 'Superficie totale']]


Consistent rows for Superficie totale: 144 - 15%


Superficie vendita  Superficie altri usi  Superficie totale
0                   292                   NaN                292
1                   800                   NaN                800
2                   726                   NaN                  0
3                   370                   NaN                370
4                   270                   NaN                270
..                  ...                   ...                ...
904                 380                   NaN                380
905                 601                   NaN                601
908                 462                   NaN                753
909                 591                   NaN                776
910                 397                   NaN                624

[767 rows x 3 columns]

Consideration: As before, the consistency is very low, primarily because many values in 'Superficie altri usi' are NaN.

In [ ]:
#Let's do it again but considering only the non null rows
CONSISTENT_ROWS = (ROWS['Superficie totale'] > 0) & (ROWS['Superficie totale'] == (ROWS['Superficie vendita'] + ROWS['Superficie altri usi']))
print('Consistent rows for Superficie totale (only notna rows): ' + str(CONSISTENT_ROWS.sum()) + ' - ' + str(int(CONSISTENT_ROWS.sum()/ROWS_COUNT*100)) + '%')
print('NON consistent rows:')
ROWS[~CONSISTENT_ROWS][['Superficie vendita', 'Superficie altri usi', 'Superficie totale']]

Consistent rows for Superficie totale (only notna rows): 144 - 92%
NON consistent rows:


Superficie vendita  Superficie altri usi  Superficie totale
19                  536                   1.0                 54
100                3500                1300.0               5880
102                1910                1100.0               3684
155                1416                  22.0               2852
172                3200                2164.0               5570
227                 380                  50.0               1200
229                 400                 450.0               1030
236                 270                 140.0                691
386                 300                 291.0                  0
570                 400                 400.0                402
903                 600                 300.0                600

Consideration: exlcuding the rows with missing values (that will be fixed later) the consistency is pretty high. <br>
However, we can distinguish different cases: there are instances where 'Superficie totale' is greater than the sum of the other two attributes (e.g., row 236) and instances where it is lower than the sum (e.g., row 570). During imputation, we should decide on a consistent approach to imputing these values.

**FUNCTIONAL DEPENDENCY DISCOVERY**

In [ ]:
# functional dependency -> same street address should correspond to always the same ZD and Codice Via
fd_via_zona = DATA.groupby(["Tipo Via", "Via"])["ZD"].nunique().max() <= 1
print("La combinazione Tipo Via + Via determina univocamente ZD?", fd_via_zona)
fd_via_cod = DATA.groupby(["Tipo Via", "Via"])["Codice Via"].nunique().max() <= 1
print("La combinazione Tipo Via + Via determina univocamente Codice Via?", fd_via_cod)


La combinazione Tipo Via + Via determina univocamente ZD? False
La combinazione Tipo Via + Via determina univocamente Codice Via? True


## **2.** Data cleaning

###  **a.** Data Transformation/Standardization

Standardization of columns names



In [ ]:
# Rename the columns, to follow underscore_convention and add unit of measurement (inplace assign the changes)
DATA.rename(columns={'Settore Merceologico': 'Settore_merceologico'}, inplace=True)
DATA.rename(columns={'Superficie vendita': 'Superficie_vendita[m²]', 'Superficie altri usi': 'Superficie_altri_usi[m²]',
                     'Superficie totale': 'Superficie_totale[m²]'}, inplace=True)

# Rename 'Via' attribute to 'Nome Via'
DATA = DATA.rename(columns={"Via": "Denominazione"})

# Rename 'ZD' to 'Zona'
DATA = DATA.rename(columns={"ZD": "Municipio"})

Standardization/transformation of values inside 'Settore_merceologico'

In [ ]:
# Change every instance of 'alimentare;non alimentare' in 'Settore_merceologico'
DATA.loc[DATA['Settore_merceologico'] == 'alimentare;non alimentare', 'Settore_merceologico'] = 'alimentare/non alimentare'

# Cut 'non alimentare;' from the special values
DATA['Settore_merceologico'] = DATA['Settore_merceologico'].str.split(';').str[-1]

In [ ]:
DATA['Tipo Via'].unique()

array(['PZA', 'RIP', 'VIA', 'VLE', 'PLE', 'CSO', 'GLL', 'FOR', 'LGO',
       'LARGO', 'BST', 'PAS', 'PTA', 'ALZ'], dtype=object)

In [ ]:
# normalize different representation of LARGO and LGO to LGO
DATA.loc[DATA['Tipo Via'] == 'LARGO', 'Tipo Via'] = 'LGO'
DATA['Tipo Via'].unique()

array(['PZA', 'RIP', 'VIA', 'VLE', 'PLE', 'CSO', 'GLL', 'FOR', 'LGO',
       'BST', 'PAS', 'PTA', 'ALZ'], dtype=object)

In [ ]:
# split Ubicazione in multiple attributes
DATA[['TIPO VIA', 'UBICAZIONE']] = DATA['Ubicazione'].str.split(" ", n=1, expand=True)
DATA.drop('Ubicazione', axis=1, inplace=True)
DATA


Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO     2.0         626          1   
1         DI PTA TICINESE    73.0        5150          6   
2    ALBERICO DA ROSCIATE     5.0        6589          7   
3     ASTESANI ALESSANDRO    17.0        1558          9   
4         MONTE NAPOLEONE     NaN         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO    42.0        2133          2   
907             GALLARATE    40.0        7420          8   
908      MAFFUCCI ANGIOLO    40.0        1276          9   
909            CASSIODORO    12.0        6359          8   
910          TESTI FULVIO    90.0        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA                                         UBICAZIONE  
0        PZA  CORDUSIO N. 2 ;pza cordusio 002; isolato:436; ...  
1        RIP                     DI PTA TICINESE N. 73 (z.d. 1)  
2        VIA                 ALBERICO DA ROSCIATE N. 5 (z.d. 7)  
3        VIA  ASTESANI ALESSANDRO N. 17 ; isolato:100; acces...  
4        VIA                MONTE NAPOLEONE num.006/a; (z.d. 1)  
..       ...                                                ...  
906      VIA  MACCHI MAURO N. 42 ; isolato:031; accesso: acc...  
907      VIA  GALLARATE N. 40 centro strada; isolato:228; pt...  
908       ff  porta g codvia 9403 num.000 ; isolato:259; acc...  
909      VLE  CASSIODORO N. 12 ; isolato:151; accesso: acces...  
910      VLE  TESTI FULVIO N. 90 ; isolato:145; accesso: acc...  

[911 rows x 12 columns]

In [ ]:
# format also 'TIPO VIA' into the same format of 'Tipo Via'
DATA.loc[DATA['TIPO VIA'] == 'LARGO', 'TIPO VIA'] = 'LGO'
print('TIPO VIA: ')
print(DATA['TIPO VIA'].unique())
Via_labels = DATA['Tipo Via'].unique()
print('Tipo Via: ')
print(Via_labels)

# replace labels like 'ff' or 'mm1' which are not valid with 'X' as placeholder
DATA.loc[~DATA['TIPO VIA'].isin(Via_labels), 'TIPO VIA'] = 'X'
print(DATA['TIPO VIA'].unique())

TIPO VIA: 
['PZA' 'RIP' 'VIA' 'VLE' 'PLE' 'CSO' 'ff' 'GLL' 'FOR' 'LGO' 'BST' 'PAS'
 'PTA' 'mm1' 'codvia' 'ALZ']
Tipo Via: 
['PZA' 'RIP' 'VIA' 'VLE' 'PLE' 'CSO' 'GLL' 'FOR' 'LGO' 'BST' 'PAS' 'PTA'
 'ALZ']
['PZA' 'RIP' 'VIA' 'VLE' 'PLE' 'CSO' 'X' 'GLL' 'FOR' 'LGO' 'BST' 'PAS'
 'PTA' 'ALZ']


In [ ]:
# Extracting the Accesso, where present, from 'UBICAZIONE'
DATA['Accesso'] = DATA['UBICAZIONE'].str.extract(r'accesso:\s*([^;]*)')

# Extracting the Civico Number from 'UBICAZIONE'
DATA['CIVICO'] = DATA['UBICAZIONE'].str.extract(r'(?i)\b(?:N\.|num.)\s*(\d+)')

# Extracting the DENOMIZAIONE from 'UBICAZIONE'
DATA[['DENOMINAZIONE', 'UBICAZIONE']] = DATA['UBICAZIONE'].str.split(" N\.|num.", n=1, expand=True)

# Extracting the MUNICIPIO from 'UBICAZIONE'
DATA['MUNICIPIO'] = DATA['UBICAZIONE'].str.extract(r'\(z\.d\.\s(\d+)\)')
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO     2.0         626          1   
1         DI PTA TICINESE    73.0        5150          6   
2    ALBERICO DA ROSCIATE     5.0        6589          7   
3     ASTESANI ALESSANDRO    17.0        1558          9   
4         MONTE NAPOLEONE     NaN         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO    42.0        2133          2   
907             GALLARATE    40.0        7420          8   
908      MAFFUCCI ANGIOLO    40.0        1276          9   
909            CASSIODORO    12.0        6359          8   
910          TESTI FULVIO    90.0        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA                                         UBICAZIONE  \
0        PZA   2 ;pza cordusio 002; isolato:436; accesso: ac...   
1        RIP                                        73 (z.d. 1)   
2        VIA                                         5 (z.d. 7)   
3        VIA   17 ; isolato:100; accesso: accesso esterno; (...   
4        VIA                                    006/a; (z.d. 1)   
..       ...                                                ...   
906      VIA   42 ; isolato:031; accesso: accesso interno; (...   
907      VIA   40 centro strada; isolato:228; pto strada:cs;...   
908        X  000 ; isolato:259; accesso: accesso interno; (...   
909      VLE   12 ; isolato:151; accesso: accesso esterno; (...   
910      VLE   90 ; isolato:145; accesso: accesso esterno; (...   

             Accesso CIVICO         DENOMINAZIONE MUNICIPIO  
0    accesso esterno      2              CORDUSIO         1  
1                NaN     73       DI PTA TICINESE         1  
2                NaN      5  ALBERICO DA ROSCIATE         7  
3    accesso esterno     17   ASTESANI ALESSANDRO         8  
4                NaN    006      MONTE NAPOLEONE          1  
..               ...    ...                   ...       ...  
906  accesso interno     42          MACCHI MAURO         2  
907  accesso esterno     40             GALLARATE         8  
908  accesso interno    000  porta g codvia 9403          9  
909  accesso esterno     12            CASSIODORO         8  
910  accesso esterno     90          TESTI FULVIO 

In [ ]:
print(DATA['Accesso'].unique())
DATA.loc[DATA['Accesso'] == 'area ap.rec.', 'Accesso'] = pd.NA
print(DATA['Accesso'].unique())
print(DATA['Accesso'].isna().sum())

['accesso esterno' nan 'accesso interno' 'area ap.rec.']
['accesso esterno' nan 'accesso interno' <NA>]
104


In [ ]:
# Accesso has 103 Null values, so since we don't deem it to be a crucial information we dropped the column
DATA.drop('Accesso', axis=1, inplace=True)
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO     2.0         626          1   
1         DI PTA TICINESE    73.0        5150          6   
2    ALBERICO DA ROSCIATE     5.0        6589          7   
3     ASTESANI ALESSANDRO    17.0        1558          9   
4         MONTE NAPOLEONE     NaN         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO    42.0        2133          2   
907             GALLARATE    40.0        7420          8   
908      MAFFUCCI ANGIOLO    40.0        1276          9   
909            CASSIODORO    12.0        6359          8   
910          TESTI FULVIO    90.0        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA                                         UBICAZIONE CIVICO  \
0        PZA   2 ;pza cordusio 002; isolato:436; accesso: ac...      2   
1        RIP                                        73 (z.d. 1)     73   
2        VIA                                         5 (z.d. 7)      5   
3        VIA   17 ; isolato:100; accesso: accesso esterno; (...     17   
4        VIA                                    006/a; (z.d. 1)    006   
..       ...                                                ...    ...   
906      VIA   42 ; isolato:031; accesso: accesso interno; (...     42   
907      VIA   40 centro strada; isolato:228; pto strada:cs;...     40   
908        X  000 ; isolato:259; accesso: accesso interno; (...    000   
909      VLE   12 ; isolato:151; accesso: accesso esterno; (...     12   
910      VLE   90 ; isolato:145; accesso: accesso esterno; (...     90   

            DENOMINAZIONE MUNICIPIO  
0                CORDUSIO         1  
1         DI PTA TICINESE         1  
2    ALBERICO DA ROSCIATE         7  
3     ASTESANI ALESSANDRO         8  
4        MONTE NAPOLEONE          1  
..                    ...       ...  
906          MACCHI MAURO         2  
907             GALLARATE         8  
908  porta g codvia 9403          9  
909            CASSIODORO         8  
910          TESTI FULVIO         9  

[911 rows x 15 columns]

In [ ]:
# let's compare now the NULL count of the original 'civico' and newly extracted 'CIVICO' from 'Ubicazione'
og_null_count = DATA['Civico'].isna().sum()
new_null_count = DATA['CIVICO'].isna().sum()

print("Original 'Civico' NULL Count:", og_null_count)
print("New 'CIVICO' NULL Count:", new_null_count)

# format the new values to the same format of the rest Civico (e.g 006 to 6)
def remove_leading_zeros(s):
  s = s.lstrip('0')
  if(s == ''):
    return '0'
  else:
    return s


DATA['CIVICO'] = DATA['CIVICO'].apply(remove_leading_zeros)
#DATA

# check also for reasonable values, for example 0 is not a valid 'Civico'
zero_count = (DATA['CIVICO'] == '0').sum()
print("Number of invalid values in 'CIVICO':", zero_count)

Original 'Civico' NULL Count: 72
New 'CIVICO' NULL Count: 0
Number of invalid values in 'CIVICO': 13


In [ ]:
# now that we extracted everything we need, we drop the column
DATA.drop('UBICAZIONE', axis=1, inplace=True)
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO     2.0         626          1   
1         DI PTA TICINESE    73.0        5150          6   
2    ALBERICO DA ROSCIATE     5.0        6589          7   
3     ASTESANI ALESSANDRO    17.0        1558          9   
4         MONTE NAPOLEONE     NaN         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO    42.0        2133          2   
907             GALLARATE    40.0        7420          8   
908      MAFFUCCI ANGIOLO    40.0        1276          9   
909            CASSIODORO    12.0        6359          8   
910          TESTI FULVIO    90.0        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA CIVICO         DENOMINAZIONE MUNICIPIO  
0        PZA      2              CORDUSIO         1  
1        RIP     73       DI PTA TICINESE         1  
2        VIA      5  ALBERICO DA ROSCIATE         7  
3        VIA     17   ASTESANI ALESSANDRO         8  
4        VIA      6      MONTE NAPOLEONE          1  
..       ...    ...                   ...       ...  
906      VIA     42          MACCHI MAURO         2  
907      VIA     40             GALLARATE         8  
908        X      0  porta g codvia 9403          9  
909      VLE     12            CASSIODORO         8  
910      VLE     90          TESTI FULVIO         9  

[911 rows x 14 columns]

In [ ]:
# data type conversions
DATA['Civico'].fillna(0, inplace=True)
DATA['Civico'] = DATA['Civico'].astype(int)
DATA['CIVICO'] = DATA['CIVICO'].astype(int)
DATA['MUNICIPIO'] = DATA['MUNICIPIO'].astype(int)
DATA.dtypes

Settore_merceologico         object
Insegna                      object
Tipo Via                     object
Denominazione                object
Civico                        int64
Codice Via                    int64
Municipio                     int64
Superficie_vendita[m²]        int64
Superficie_altri_usi[m²]    float64
Superficie_totale[m²]         int64
TIPO VIA                     object
CIVICO                        int64
DENOMINAZIONE                object
MUNICIPIO                     int64
dtype: object

### **b.** Error Detection and Correction

In [ ]:
# let's check for correctness of 'Civico' attribute comparing it to the version 'CIVICO' extracted from 'Ubicazione'
# find tuples where the 2 values are different
Civico_comparison = DATA[DATA['Civico'] != DATA['CIVICO']]
Civico_comparison

Settore_merceologico       Insegna Tipo Via           Denominazione  \
4                          NaN           NaN      VIA         MONTE NAPOLEONE   
7                          NaN     esselunga      VLE  VIGLIANI PAOLO ONORATO   
8                          NaN  in s mercato      VIA           DELLE BETULLE   
17   alimentare/non alimentare           NaN      VIA                   EDOLO   
25   alimentare/non alimentare           NaN      CSO                VERCELLI   
..                         ...           ...      ...                     ...   
859             non alimentare         smart      GLL              SAN BABILA   
879             non alimentare       tiffany      VIA             DELLA SPIGA   
888             non alimentare      vannucci      GLL              SAN BABILA   
891             non alimentare       verzeri      VIA            VILLAPIZZONE   
908  tabella speciale farmacie      farmacia      VIA        MAFFUCCI ANGIOLO   

     Civico  Codice Via  Municipio  Superficie_vendita[m²]  \
4         0         219          1                     270   
7         0        6422          8                    1225   
8         0        6828          7                     620   
17       26        1217          2                     589   
25       20        6193          7                    4413   
..      ...         ...        ...                     ...   
859       0         360          1                     450   
879       0         226          1                     266   
888       0         360          1                     380   
891       0        7272          8                     252   
908      40        1276          9                     462   

     Superficie_altri_usi[m²]  Superficie_totale[m²] TIPO VIA  CIVICO  \
4                         NaN                    270      VIA       6   
7                         NaN                   1225      VLE      59   
8                       766.0                   1386      VIA      12   
17                        NaN                    589        X       0   
25                        NaN                   6500      VIA       0   
..                        ...                    ...      ...     ...   
859                       NaN                    450      GLL       4   
879                       NaN                    266      VIA      19   
888                       NaN                    505      GLL       4   
891                       NaN                    252      VIA      12   
908                       NaN                    753        X       0   

                                         DENOMINAZIONE  MUNICIPIO  
4                                     MONTE NAPOLEONE           1  
7                              VIGLIANI PAOLO ONORATO           8  
8                                       DELLE BETULLE           7  
17                                central codvia 9401           2  
25   ADRIANO PUBLIO ELIO pii.marelli-cascina s.gius...          7  
..                                                 ...        ...  
859                                        SAN BABILA           1  
879                                       DELLA SPIGA           1  
888                                        SAN BABILA           1  
891                                      VILLAPIZZONE           8  
908                               porta g codvia 9403           9  

[108 rows x 14 columns]

In [ ]:
# now we take the value from 'CIVICO' where 'Civico' is 0 and drop the 'CIVICO' column
DATA.loc[DATA['Civico'] == 0, 'Civico'] = DATA.loc[DATA['Civico'] == 0, 'CIVICO']
DATA.drop('CIVICO', axis=1, inplace=True)
DATA


Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO       2         626          1   
1         DI PTA TICINESE      73        5150          6   
2    ALBERICO DA ROSCIATE       5        6589          7   
3     ASTESANI ALESSANDRO      17        1558          9   
4         MONTE NAPOLEONE       6         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO      42        2133          2   
907             GALLARATE      40        7420          8   
908      MAFFUCCI ANGIOLO      40        1276          9   
909            CASSIODORO      12        6359          8   
910          TESTI FULVIO      90        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA         DENOMINAZIONE  MUNICIPIO  
0        PZA              CORDUSIO          1  
1        RIP       DI PTA TICINESE          1  
2        VIA  ALBERICO DA ROSCIATE          7  
3        VIA   ASTESANI ALESSANDRO          8  
4        VIA      MONTE NAPOLEONE           1  
..       ...                   ...        ...  
906      VIA          MACCHI MAURO          2  
907      VIA             GALLARATE          8  
908        X  porta g codvia 9403           9  
909      VLE            CASSIODORO          8  
910      VLE          TESTI FULVIO          9  

[911 rows x 13 columns]

In [ ]:
# now let's see how many invalid Civico we have
zero_count = (DATA['Civico'] == 0).sum()
print("Number of invalid values in 'Civico':", zero_count)

Number of invalid values in 'Civico': 4


In [ ]:
# 4 is a pretty small number so we drop those rows
DATA = DATA.drop(DATA[DATA['Civico'] == 0].index)
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO       2         626          1   
1         DI PTA TICINESE      73        5150          6   
2    ALBERICO DA ROSCIATE       5        6589          7   
3     ASTESANI ALESSANDRO      17        1558          9   
4         MONTE NAPOLEONE       6         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO      42        2133          2   
907             GALLARATE      40        7420          8   
908      MAFFUCCI ANGIOLO      40        1276          9   
909            CASSIODORO      12        6359          8   
910          TESTI FULVIO      90        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA         DENOMINAZIONE  MUNICIPIO  
0        PZA              CORDUSIO          1  
1        RIP       DI PTA TICINESE          1  
2        VIA  ALBERICO DA ROSCIATE          7  
3        VIA   ASTESANI ALESSANDRO          8  
4        VIA      MONTE NAPOLEONE           1  
..       ...                   ...        ...  
906      VIA          MACCHI MAURO          2  
907      VIA             GALLARATE          8  
908        X  porta g codvia 9403           9  
909      VLE            CASSIODORO          8  
910      VLE          TESTI FULVIO          9  

[907 rows x 13 columns]

In [ ]:
# now check for consistency between the 'TIPO VIA' and the original 'Tipo Via' consistency
comparison_tipo_via = DATA[DATA['TIPO VIA'] != DATA['Tipo Via']]
comparison_tipo_via
#comparison_tipo_via.shape[0]

Settore_merceologico                   Insegna Tipo Via  \
17   alimentare/non alimentare                       NaN      VIA   
25   alimentare/non alimentare                       NaN      CSO   
44   alimentare/non alimentare                       NaN      VLE   
68   alimentare/non alimentare                 carrefour      VIA   
70   alimentare/non alimentare                 carrefour      VIA   
104  alimentare/non alimentare                     conad      PLE   
108  alimentare/non alimentare                     conad      VIA   
150  alimentare/non alimentare                 free shop      VIA   
199  alimentare/non alimentare                   oviesse      RIP   
208  alimentare/non alimentare                       pam      VLE   
233  alimentare/non alimentare                 punto sma      VLE   
308             non alimentare                       NaN      VIA   
385             non alimentare                       NaN      CSO   
419             non alimentare                       NaN      CSO   
432             non alimentare                       NaN      CSO   
457             non alimentare                       NaN      VLE   
558             non alimentare                       NaN      VIA   
569             non alimentare                       NaN      VIA   
585             non alimentare                       NaN      VIA   
601             non alimentare  aica concessionaria fiat      VIA   
661             non alimentare         cervi arredamenti      CSO   
772             non alimentare       la rinascente duomo      CSO   
785             non alimentare  lucky music strumenti m.      VIA   
908  tabella speciale farmacie                  farmacia      VIA   

               Denominazione  Civico  Codice Via  Municipio  \
17                     EDOLO      26        1217          2   
25                  VERCELLI      20        6193          7   
44              TESTI FULVIO     260        1441          9   
68         MURATORI LODOVICO      27        4076          4   
70          MAFFUCCI ANGIOLO       4        1276          9   
104        BAIAMONTI ANTONIO       4        7235          9   
108  VENINI GIULIO E CORRADO      87        2258          2   
150             DEI TRANSITI      20        2284          2   
199          DI PTA TICINESE      73        5150          6   
208                    MONZA     113        2274          2   
233                     ZARA     123        1170          9   
308        MAGGI CARLO MARIA      10        7115          1   
385             BUENOS AIRES       2        2129          3   
419             BUENOS AIRES      47        2129          3   
432                 SEMPIONE      51        7137          8   
457                PAPINIANO      12        5097          1   
558           MANZOTTI LUIGI      24        1300          9   
569            BRIZI EUGENIO       4        4186          4   
585                PALMANOVA      65        2390          2   
601       SISMONDI GIANCARLO      70        3256          4   
661                 MONFORTE      19         348          1   
772     VITTORIO EMANUELE II      11         214          1   
785           SODERINI LUIGI      54        6675          6   
908         MAFFUCCI ANGIOLO      40        1276          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
17                      589                       NaN                    589   
25                     4413                       NaN                   6500   
44                     4280                       NaN                   5474   
68                     2100                       NaN                   3202   
70                      600                       NaN                   1070   
104                    1166                       NaN                   1166   
108                     680                       NaN                   1190   
150                     577                       NaN               

In [ ]:
# check comparison for where Tipo via is different but Denominazione is the same
comparison_tipo_via_denominazione = DATA[(DATA['TIPO VIA'] != DATA['Tipo Via']) & (DATA['Denominazione'] == DATA['DENOMINAZIONE'])]
comparison_tipo_via_denominazione.shape[0]

0

In [ ]:
# sort the dataframe by  'Denominazione' and 'Tipo Via'
sorted_DATA = DATA.sort_values(by=['Denominazione', 'Tipo Via'])
sorted_DATA

Settore_merceologico    Insegna Tipo Via      Denominazione  Civico  \
94   alimentare/non alimentare  carrefour      VLE            ABRUZZI      54   
153  alimentare/non alimentare         gs      VLE            ABRUZZI      10   
554             non alimentare        NaN      VLE            ABRUZZI      51   
555             non alimentare        NaN      VLE            ABRUZZI      13   
359             non alimentare        NaN      VIA  ACHILLINI CLAUDIO       2   
..                         ...        ...      ...                ...     ...   
552             non alimentare        NaN      VIA    ZANELLA GIACOMO      36   
553             non alimentare        NaN      VIA    ZANELLA GIACOMO      61   
142  alimentare/non alimentare  esselunga      VLE               ZARA     123   
233  alimentare/non alimentare  punto sma      VLE               ZARA     123   
122  alimentare/non alimentare   discount      VIA      ZOCCHI CESARE       1   

     Codice Via  Municipio  Superficie_vendita[m²]  Superficie_altri_usi[m²]  \
94         2177          3                     370                       NaN   
153        2177          3                     800                       NaN   
554        2177          3                     292                       NaN   
555        2177          3                     300                       NaN   
359        1605          9                    1500                       NaN   
..          ...        ...                     ...                       ...   
552        3257          4                     378                       NaN   
553        3257          4                    1500                     455.0   
142        1170          9                    1700                       NaN   
233        1170          9                     505                       NaN   
122        1301          9                     300                       NaN   

     Superficie_totale[m²] TIPO VIA  \
94                     413      VLE   
153                   1400      VLE   
554                    292      VLE   
555                    300      VLE   
359                   1500      VIA   
..                     ...      ...   
552                    378      VIA   
553                   1955      VIA   
142                   1700      VLE   
233                    900      VIA   
122                    450      VIA   

                                 DENOMINAZIONE  MUNICIPIO  
94                                     ABRUZZI          3  
153                                   ABRUZZI           3  
554                                    ABRUZZI          3  
555                                   ABRUZZI           3  
359                          ACHILLINI CLAUDIO          9  
..                                         ...        ...  
552                            ZANELLA GIACOMO          4  
553                            ZANELLA GIACOMO          4  
142                                       ZARA          9  
233  TARTINI GIUSEPPE aff. az. tacit. rinnov.           9  
122                              ZOCCHI CESARE          9  

[907 rows x 13 columns]

In [ ]:
# results of the functional dependency checks
print(fd_via_zona)
print(fd_via_cod)

False
True


In [ ]:
# for the zona locate the violations
groups = DATA.groupby(["Tipo Via", "Denominazione"])["Municipio"].nunique()
violations = groups[groups > 1]
violations



Tipo Via  Denominazione    
CSO       INDIPENDENZA         2
          LODI                 2
          SEMPIONE             2
VIA       CASATI FELICE        2
          IMPERIA              2
          SAN GREGORIO         2
          SARPI FRA' PAOLO     2
          SETTEMBRINI LUIGI    2
VLE       PIAVE                2
Name: Municipio, dtype: int64

In [ ]:
# the same for the counterpart rows
GROUPS = DATA.groupby(["TIPO VIA", "DENOMINAZIONE"])["MUNICIPIO"].nunique()
VIOLATIONS = GROUPS[GROUPS > 1]
VIOLATIONS

TIPO VIA  DENOMINAZIONE      
CSO       INDIPENDENZA           2
          LODI                   2
          SEMPIONE               2
          VERCELLI               2
RIP       DI PTA TICINESE        2
VIA       ASTESANI ALESSANDRO    2
          CASATI FELICE          2
          IMPERIA                2
          SAN GREGORIO           2
          SARPI FRA' PAOLO       2
          SETTEMBRINI LUIGI      2
VLE       PIAVE                  2
Name: MUNICIPIO, dtype: int64

In [ ]:
# Extract lists of "Tipo Via" and "Denominazione" into list to use for filtering
tipo_via_list = violations.index.get_level_values('Tipo Via').tolist()
denominazione_list = violations.index.get_level_values('Denominazione').tolist()

TIPO_VIA_LIST = VIOLATIONS.index.get_level_values('TIPO VIA').tolist()
DENOMINAZIONE_LIST = VIOLATIONS.index.get_level_values('DENOMINAZIONE').tolist()

# Print the lists
print("List of Tipo Via:", tipo_via_list)
print("List of Denominazione:", denominazione_list)


List of Tipo Via: ['CSO', 'CSO', 'CSO', 'VIA', 'VIA', 'VIA', 'VIA', 'VIA', 'VLE']
List of Denominazione: ['INDIPENDENZA', 'LODI', 'SEMPIONE', 'CASATI FELICE', 'IMPERIA', 'SAN GREGORIO', "SARPI FRA' PAOLO", 'SETTEMBRINI LUIGI', 'PIAVE']


In [ ]:
violating_rows = sorted_DATA[(sorted_DATA['Tipo Via'].isin(tipo_via_list) & sorted_DATA['Denominazione'].isin(denominazione_list)) |
 (sorted_DATA['TIPO VIA'].isin(TIPO_VIA_LIST) & sorted_DATA['DENOMINAZIONE'].isin(DENOMINAZIONE_LIST))]
violating_rows

Settore_merceologico                    Insegna Tipo Via  \
3                          NaN                        NaN      VIA   
251  alimentare/non alimentare  sma supermercati alimenta      VIA   
117  alimentare/non alimentare                  di per di      VIA   
147  alimentare/non alimentare              euro discount      VIA   
1                          NaN                        NaN      RIP   
358             non alimentare                        NaN      RIP   
691             non alimentare                     ecliss      RIP   
692             non alimentare          ecliss top garden      RIP   
440             non alimentare                        NaN      VIA   
659             non alimentare            centro marmitte      VIA   
309             non alimentare                        NaN      CSO   
310             non alimentare                        NaN      CSO   
126  alimentare/non alimentare                       ecom      CSO   
248  alimentare/non alimentare  sma supermercati alimenta      CSO   
312             non alimentare                        NaN      CSO   
313             non alimentare                        NaN      CSO   
314             non alimentare                        NaN      CSO   
645             non alimentare             bruno castoldi      CSO   
662             non alimentare               chateau d ax      CSO   
663             non alimentare               chateau d ax      CSO   
141  alimentare/non alimentare                  esselunga      VLE   
868             non alimentare       spotti modern living      VLE   
496             non alimentare                        NaN      VIA   
497             non alimentare                        NaN      VIA   
49   alimentare/non alimentare                        NaN      VIA   
88   alimentare/non alimentare                  carrefour      VIA   
267  alimentare/non alimentare       supermercati di x di      VIA   
510             non alimentare                        NaN      VIA   
511             non alimentare                        NaN      VIA   
321             non alimentare                        NaN      CSO   
432             non alimentare                        NaN      CSO   
830             non alimentare                    piaggio      CSO   
856             non alimentare                   sempione      CSO   
622             non alimentare                     avalon      VIA   
631             non alimentare  belmonte camiciaio italia      VIA   
69   alimentare/non alimentare                  carrefour      CSO   
325             non alimentare                        NaN      CSO   
326             non alimentare                        NaN      CSO   
602             non alimentare  alberto germani sportrend      CSO   
640             non alimentare                     borghi      CSO   
684             non alimentare                della fonte      CSO   
686             non alimentare                        dev      CSO   
729             non alimentare              germani sport      CSO   
885             non alimentare  united colors of benetton      CSO   

           Denominazione  Civico  Codice Via  Municipio  \
3    ASTESANI ALESSANDRO      17        1558          9   
251  ASTESANI ALESSANDRO      46        1558          9   
117        CASATI FELICE      32        2122          2   
147        CASATI FELICE       8        2122          3   
1        DI PTA TICINESE      73        5150          6   
358      DI PTA TICINESE      47        5150          6   
691      DI PTA TICINESE      73        5150          6   
692      DI PTA TICINESE      73        5150          6   
440              IMPERIA      15        5266          5   
659              IMPERIA      33        5266          6   
309         INDIPENDENZA       1        3118          3   
310         INDIPENDENZA      24        3118          4   
126                 LODI      65        4068          4   
248                 LODI     130 

In [ ]:
violating_rows.shape[0]

44

In [ ]:
violating_rows.index

Index([  3, 251, 117, 147,   1, 358, 691, 692, 440, 659, 309, 310, 126, 248,
       312, 313, 314, 645, 662, 663, 141, 868, 496, 497,  49,  88, 267, 510,
       511, 321, 432, 830, 856, 622, 631,  69, 325, 326, 602, 640, 684, 686,
       729, 885],
      dtype='int64')

In [ ]:
# function for the majority voting
def majority_value(series):
  return series.mode()[0]

groups = sorted_DATA.groupby(['Tipo Via', 'Denominazione'])
violating_rows['Municipio'] = groups['Municipio'].transform(majority_value)

#GROUPS = sorted_DATA.groupby(['TIPO VIA', 'DENOMINAZIONE'])
violating_rows['MUNICIPIO'] = groups['MUNICIPIO'].transform(majority_value)

violating_rows

Settore_merceologico                    Insegna Tipo Via  \
3                          NaN                        NaN      VIA   
251  alimentare/non alimentare  sma supermercati alimenta      VIA   
117  alimentare/non alimentare                  di per di      VIA   
147  alimentare/non alimentare              euro discount      VIA   
1                          NaN                        NaN      RIP   
358             non alimentare                        NaN      RIP   
691             non alimentare                     ecliss      RIP   
692             non alimentare          ecliss top garden      RIP   
440             non alimentare                        NaN      VIA   
659             non alimentare            centro marmitte      VIA   
309             non alimentare                        NaN      CSO   
310             non alimentare                        NaN      CSO   
126  alimentare/non alimentare                       ecom      CSO   
248  alimentare/non alimentare  sma supermercati alimenta      CSO   
312             non alimentare                        NaN      CSO   
313             non alimentare                        NaN      CSO   
314             non alimentare                        NaN      CSO   
645             non alimentare             bruno castoldi      CSO   
662             non alimentare               chateau d ax      CSO   
663             non alimentare               chateau d ax      CSO   
141  alimentare/non alimentare                  esselunga      VLE   
868             non alimentare       spotti modern living      VLE   
496             non alimentare                        NaN      VIA   
497             non alimentare                        NaN      VIA   
49   alimentare/non alimentare                        NaN      VIA   
88   alimentare/non alimentare                  carrefour      VIA   
267  alimentare/non alimentare       supermercati di x di      VIA   
510             non alimentare                        NaN      VIA   
511             non alimentare                        NaN      VIA   
321             non alimentare                        NaN      CSO   
432             non alimentare                        NaN      CSO   
830             non alimentare                    piaggio      CSO   
856             non alimentare                   sempione      CSO   
622             non alimentare                     avalon      VIA   
631             non alimentare  belmonte camiciaio italia      VIA   
69   alimentare/non alimentare                  carrefour      CSO   
325             non alimentare                        NaN      CSO   
326             non alimentare                        NaN      CSO   
602             non alimentare  alberto germani sportrend      CSO   
640             non alimentare                     borghi      CSO   
684             non alimentare                della fonte      CSO   
686             non alimentare                        dev      CSO   
729             non alimentare              germani sport      CSO   
885             non alimentare  united colors of benetton      CSO   

           Denominazione  Civico  Codice Via  Municipio  \
3    ASTESANI ALESSANDRO      17        1558          9   
251  ASTESANI ALESSANDRO      46        1558          9   
117        CASATI FELICE      32        2122          2   
147        CASATI FELICE       8        2122          2   
1        DI PTA TICINESE      73        5150          6   
358      DI PTA TICINESE      47        5150          6   
691      DI PTA TICINESE      73        5150          6   
692      DI PTA TICINESE      73        5150          6   
440              IMPERIA      15        5266          5   
659              IMPERIA      33        5266          5   
309         INDIPENDENZA       1        3118          3   
310         INDIPENDENZA      24        3118          3   
126                 LODI      65        4068          4   
248                 LODI     130 

Seeing the result as satisfying we apply the same to original Dataframe

In [ ]:
# apply to the original dataframe
DATA['Municipio'] = groups['Municipio'].transform(majority_value)
DATA['MUNICIPIO'] = groups['MUNICIPIO'].transform(majority_value)
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO       2         626          1   
1         DI PTA TICINESE      73        5150          6   
2    ALBERICO DA ROSCIATE       5        6589          7   
3     ASTESANI ALESSANDRO      17        1558          9   
4         MONTE NAPOLEONE       6         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO      42        2133          2   
907             GALLARATE      40        7420          8   
908      MAFFUCCI ANGIOLO      40        1276          9   
909            CASSIODORO      12        6359          8   
910          TESTI FULVIO      90        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
0                       292                       NaN                    292   
1                       800                       NaN                    800   
2                       726                       NaN                      0   
3                       370                       NaN                    370   
4                       270                       NaN                    270   
..                      ...                       ...                    ...   
906                     350                     475.0                    825   
907                     800                     100.0                    900   
908                     462                       NaN                    753   
909                     591                       NaN                    776   
910                     397                       NaN                    624   

    TIPO VIA         DENOMINAZIONE  MUNICIPIO  
0        PZA              CORDUSIO          1  
1        RIP       DI PTA TICINESE          6  
2        VIA  ALBERICO DA ROSCIATE          7  
3        VIA   ASTESANI ALESSANDRO          8  
4        VIA      MONTE NAPOLEONE           1  
..       ...                   ...        ...  
906      VIA          MACCHI MAURO          2  
907      VIA             GALLARATE          8  
908        X  porta g codvia 9403           9  
909      VLE            CASSIODORO          8  
910      VLE          TESTI FULVIO          9  

[907 rows x 13 columns]

In [ ]:
# check comparison for where Zona and ZONA are different
comparison_zona = DATA[DATA['Municipio'] != DATA['MUNICIPIO']]
print(comparison_zona.shape[0])  # not relevant result
# since the policy adopted is to drop the Original 'Ubicazione' data check only those where Via and Denominazione are the same
comparison_zona_via_denominazione = DATA[(DATA['Municipio'] != DATA['MUNICIPIO']) & (DATA['Tipo Via'] == DATA['TIPO VIA']) & (DATA['Denominazione'] == DATA['DENOMINAZIONE'])]
print(comparison_zona_via_denominazione.shape[0])
comparison_zona_via_denominazione

16
12


Settore_merceologico                    Insegna Tipo Via  \
3                          NaN                        NaN      VIA   
217  alimentare/non alimentare               penny market      VIA   
251  alimentare/non alimentare  sma supermercati alimenta      VIA   
368             non alimentare                        NaN      VIA   
387             non alimentare                        NaN      VIA   
389             non alimentare                        NaN      VIA   
512             non alimentare                        NaN      VIA   
536             non alimentare                        NaN      VIA   
537             non alimentare                        NaN      VIA   
538             non alimentare                        NaN      VIA   
540             non alimentare                        NaN      VIA   
607             non alimentare         argenteria dabbene      LGO   

           Denominazione  Civico  Codice Via  Municipio  \
3    ASTESANI ALESSANDRO      17        1558          9   
217    CARNEVALI ANTONIO     116        1268          9   
251  ASTESANI ALESSANDRO      46        1558          9   
368   ARNALDO DA BRESCIA       4        1151          9   
387     CANTONI GIOVANNI       7        6206          7   
389    CARNEVALI ANTONIO      28        1268          9   
512               SAVONA      25        5122          6   
536  TRAIANO MARCO ULPIO      79        7157          8   
537  TRAIANO MARCO ULPIO      79        7157          8   
538  TRAIANO MARCO ULPIO      79        7157          8   
540           VALTELLINA      17        1188          9   
607       TREVES CLAUDIO       2        1026          1   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
3                       370                       NaN                    370   
217                     765                       NaN                      0   
251                     705                       NaN                   1685   
368                     607                       NaN                    607   
387                     600                       NaN                    600   
389                     300                      50.0                    350   
512                     265                       NaN                    265   
536                     559                       NaN                    743   
537                    1012                       NaN                   1102   
538                     375                       NaN                    503   
540                     358                       NaN                    358   
607                     280                     180.0                    460   

    TIPO VIA        DENOMINAZIONE  MUNICIPIO  
3        VIA  ASTESANI ALESSANDRO          8  
217      VIA    CARNEVALI ANTONIO          7  
251      VIA  ASTESANI ALESSANDRO          8  
368      VIA   ARNALDO DA BRESCIA          2  
387      VIA     CANTONI GIOVANNI          6  
389      VIA    CARNEVALI ANTONIO          7  
512      VIA               SAVONA          5  
536      VIA  TRAIANO MARCO ULPIO          9  
537      VIA  TRAIANO MARCO ULPIO          9  
538      VIA  TRAIANO MARCO ULPIO          9  
540      VIA           VALTELLINA          7  
607      LGO       TREVES CLAUDIO          3

#### OUTLIER ANALYSIS

Let's detect potential outliers for the 'position-related' attributes.

In [ ]:
# let's detect outliers in this distributions
def ZS(data, threshold):
    mean = np.mean(data)
    sd = np.std(data) # calculate standard deviation
    outliers = [] # create empty list to store outliers
    for i in data: # detect outliers
        z = (i - mean) / sd  # calculate z-score
        if abs(z) > threshold:  # identify outliers
            outliers.append(i)  # add to the empty list

    return outliers

# save in numpyArray the values of Codice Via, grouped by Zona
codvia_zona = DATA.groupby('Municipio')['Codice Via'].apply(list).to_numpy()
print(codvia_zona)

[list([626, 219, 208, 532, 7115, 218, 305, 1, 714, 718, 5097, 4026, 1016, 1036, 404, 555, 711, 5180, 7112, 5097, 2179, 586, 7132, 5164, 305, 541, 5090, 518, 7121, 7121, 518, 219, 1066, 541, 300, 1010, 7115, 526, 604, 218, 218, 348, 238, 238, 238, 214, 214, 214, 214, 214, 711, 305, 296, 297, 331, 102, 116, 345, 216, 216, 1040, 514, 515, 7116, 224, 224, 301, 719, 574, 233, 362, 140, 123, 341, 313, 313, 313, 313, 146, 613, 190, 190, 410, 6156, 5095, 230, 230, 516, 5097, 219, 219, 219, 219, 564, 5090, 5183, 143, 1051, 3010, 351, 1046, 1036, 213, 349, 5188, 535, 535, 222, 222, 222, 222, 228, 1028, 1028, 517, 1020, 543, 543, 543, 543, 223, 6219, 361, 597, 6213, 1112, 218, 620, 218, 212, 560, 1026, 230, 230, 230, 230, 313, 348, 219, 205, 3059, 613, 222, 604, 234, 214, 518, 543, 313, 218, 609, 711, 224, 604, 298, 211, 209, 348, 219, 339, 219, 219, 219, 300, 230, 543, 238, 226, 238, 226, 1, 543, 219, 98, 230, 405, 120, 299, 222, 2102, 226, 222, 315, 219, 360, 612, 214, 214, 303, 222, 219, 513, 

In [ ]:
# compute the outliers per Zona
outliers_by_zone = []
for i, zone in enumerate(codvia_zona):
    temp = ZS(zone, 3)
    outliers_by_zone.append(temp)
    print(f"Municipio {i+1}: {temp}")

Municipio 1: [7115, 7112, 7132, 7121, 7121, 7115, 7116, 6156, 6219, 6213, 7085, 7121]
Municipio 2: []
Municipio 3: []
Municipio 4: []
Municipio 5: []
Municipio 6: []
Municipio 7: []
Municipio 8: [6422, 6360, 6140, 6354, 6366, 6359]
Municipio 9: [7235, 7235]


In [ ]:
flat_outliers = [item for sublist in outliers_by_zone for item in sublist]
Outliers_DATA = DATA[DATA['Codice Via'].isin(flat_outliers)]
Outliers_DATA

Settore_merceologico                  Insegna Tipo Via  \
7                          NaN                esselunga      VLE   
15                  alimentare                punto sma      VIA   
104  alimentare/non alimentare                    conad      PLE   
123  alimentare/non alimentare                 di  x di      VIA   
174  alimentare/non alimentare  kathay china food store      VIA   
226  alimentare/non alimentare                punto sma      PLE   
230  alimentare/non alimentare                punto sma      VIA   
268  alimentare/non alimentare             supermercato      VIA   
282  alimentare/non alimentare                     unes      VLE   
308             non alimentare                      NaN      VIA   
337             non alimentare                      NaN      LGO   
372             non alimentare                      NaN      VIA   
444             non alimentare                      NaN      VIA   
469             non alimentare                      NaN      VIA   
546             non alimentare                      NaN      VIA   
564             non alimentare                      NaN      VLE   
566             non alimentare                      NaN      VLE   
766             non alimentare         la casa italiana      VLE   
788             non alimentare        marco polo expert      VIA   
909  tabella speciale farmacie      farmacia cassiodoro      VLE   

              Denominazione  Civico  Codice Via  Municipio  \
7    VIGLIANI PAOLO ONORATO      59        6422          8   
15        MAGGI CARLO MARIA      10        7115          1   
104       BAIAMONTI ANTONIO       4        7235          9   
123        BERTANI AGOSTINO       2        7112          1   
174         ROSMINI ANTONIO      11        7132          1   
226       BAIAMONTI ANTONIO       4        7235          9   
230          CANONICA LUIGI      54        7121          1   
268          CANONICA LUIGI      54        7121          1   
282               BELISARIO       3        6360          8   
308       MAGGI CARLO MARIA      10        7115          1   
337             DOMODOSSOLA       1        6140          8   
372    BALESTRIERI DOMENICO       6        7116          1   
444        LEOPARDI GIACOMO       7        6156          1   
469          NIEVO IPPOLITO      41        6354          8   
546      VICO GIAN BATTISTA      14        6219          1   
564     DI PORTA VERCELLINA      16        6213          1   
566                EGINARDO      15        6366          8   
766                 ELVEZIA      22        7085          1   
788          CANONICA LUIGI      55        7121          1   
909              CASSIODORO      12        6359          8   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  \
7                      1225                       NaN                   1225   
15                      280                       NaN                    458   
104                    1166                       NaN                   1166   
123                     260                       NaN                    365   
174                     259                       NaN                    259   
226                     355                       NaN                    566   
230                     388                       NaN                    833   
268                     397                       NaN                    397   
282                     650                       NaN                   1770   
308                     725                     130.0                    855   
337                     563                       NaN                   1030   
372                     310                       NaN                      0   
444                     370                      50.0                    420   
469                     470                       NaN                    470   
546                     307                      15.0                    322  

In [ ]:
# Now let's make the same check as before for this subset
comparison_zona_via_denominazione['Codice Via'].isin(flat_outliers)

3      False
217    False
251    False
368    False
387    False
389    False
512    False
536    False
537    False
538    False
540    False
607    False
Name: Codice Via, dtype: bool

In [ ]:
# last check: see if violating_rows were in the flat_outliers and see if the mode was really a suitable solution
violating_rows['Codice Via'].isin(flat_outliers)

3      False
251    False
117    False
147    False
1      False
358    False
691    False
692    False
440    False
659    False
309    False
310    False
126    False
248    False
312    False
313    False
314    False
645    False
662    False
663    False
141    False
868    False
496    False
497    False
49     False
88     False
267    False
510    False
511    False
321    False
432    False
830    False
856    False
622    False
631    False
69     False
325    False
326    False
602    False
640    False
684    False
686    False
729    False
885    False
Name: Codice Via, dtype: bool

In [ ]:
# since we have zero denominazione with different tipo Via we can keep the original Tipo Via and Denominazione
# also there's no difference in Zona between the 2 where codice Via is a possible outlier, so also ZONA can be dropped
DATA = DATA.drop(columns=['TIPO VIA', 'DENOMINAZIONE', 'MUNICIPIO'])
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN                  NaN      PZA   
1                            NaN                  NaN      RIP   
2                            NaN                  NaN      VIA   
3                            NaN                  NaN      VIA   
4                            NaN                  NaN      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio                  NaN      VIA   
907  tabella speciale carburanti                  NaN      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO       2         626          1   
1         DI PTA TICINESE      73        5150          6   
2    ALBERICO DA ROSCIATE       5        6589          7   
3     ASTESANI ALESSANDRO      17        1558          9   
4         MONTE NAPOLEONE       6         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO      42        2133          2   
907             GALLARATE      40        7420          8   
908      MAFFUCCI ANGIOLO      40        1276          9   
909            CASSIODORO      12        6359          8   
910          TESTI FULVIO      90        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  
0                       292                       NaN                    292  
1                       800                       NaN                    800  
2                       726                       NaN                      0  
3                       370                       NaN                    370  
4                       270                       NaN                    270  
..                      ...                       ...                    ...  
906                     350                     475.0                    825  
907                     800                     100.0                    900  
908                     462                       NaN                    753  
909                     591                       NaN                    776  
910                     397                       NaN                    624  

[907 rows x 10 columns]

From from domain knowledge we identify that for 'Superficie..' attributes values such as 0 or 1 as to be considered outliers.
Imputation method: simply invalidate those values (by setting them to Nan) and solve everything in the missing values imputation step.


From the profiling step we saw that some value of the attributes 'Superficie...' are = 0, or = 1, those are to be considered as missing values.

In [ ]:
#First of all let's 'invalidate' all 'Superficie..' attributes values = 0 and = 1 by putting it as NaN, so that they will all be treated in the missing value imputation step.
outliers_values = [0, 1]
outliers_row = DATA[(DATA['Superficie_vendita[m²]'].isin(outliers_values)) |
                    (DATA['Superficie_altri_usi[m²]'].isin(outliers_values)) |
                    (DATA['Superficie_totale[m²]'].isin(outliers_values))]
DATA.loc[DATA['Superficie_vendita[m²]'].isin(outliers_values), 'Superficie_vendita[m²]'] = np.nan
DATA.loc[DATA['Superficie_altri_usi[m²]'].isin(outliers_values), 'Superficie_altri_usi[m²]'] = np.nan
DATA.loc[DATA['Superficie_totale[m²]'].isin(outliers_values), 'Superficie_totale[m²]'] = np.nan

#### MISSING VALUE ANALYSIS

In [ ]:
# fill the missing value of insegna with "Mancante"
DATA["Insegna"].fillna("Mancante", inplace=True)
DATA

Settore_merceologico              Insegna Tipo Via  \
0                            NaN             Mancante      PZA   
1                            NaN             Mancante      RIP   
2                            NaN             Mancante      VIA   
3                            NaN             Mancante      VIA   
4                            NaN             Mancante      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio             Mancante      VIA   
907  tabella speciale carburanti             Mancante      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO       2         626          1   
1         DI PTA TICINESE      73        5150          6   
2    ALBERICO DA ROSCIATE       5        6589          7   
3     ASTESANI ALESSANDRO      17        1558          9   
4         MONTE NAPOLEONE       6         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO      42        2133          2   
907             GALLARATE      40        7420          8   
908      MAFFUCCI ANGIOLO      40        1276          9   
909            CASSIODORO      12        6359          8   
910          TESTI FULVIO      90        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  
0                     292.0                       NaN                  292.0  
1                     800.0                       NaN                  800.0  
2                     726.0                       NaN                    NaN  
3                     370.0                       NaN                  370.0  
4                     270.0                       NaN                  270.0  
..                      ...                       ...                    ...  
906                   350.0                     475.0                  825.0  
907                   800.0                     100.0                  900.0  
908                   462.0                       NaN                  753.0  
909                   591.0                       NaN                  776.0  
910                   397.0                       NaN                  624.0  

[907 rows x 10 columns]

We observed from the profiling step that there are a few missing values in the 'Settore_merceologico' column. For some of these, we can perform accurate imputation using the 'Insegna' column. For the remaining ones, where an accurate estimate is not possible, we will impute them using the mode of this attribute across the dataset.

In [ ]:
DATA[DATA['Settore_merceologico'].isna()]

Settore_merceologico               Insegna Tipo Via  \
0                   NaN              Mancante      PZA   
1                   NaN              Mancante      RIP   
2                   NaN              Mancante      VIA   
3                   NaN              Mancante      VIA   
4                   NaN              Mancante      VIA   
6                   NaN             esselunga      VIA   
7                   NaN             esselunga      VLE   
8                   NaN          in s mercato      VIA   
9                   NaN  la rinascente s.p.a.      VIA   
10                  NaN                   pam      VIA   
11                  NaN           supermarket      VIA   

             Denominazione  Civico  Codice Via  Municipio  \
0                 CORDUSIO       2         626          1   
1          DI PTA TICINESE      73        5150          6   
2     ALBERICO DA ROSCIATE       5        6589          7   
3      ASTESANI ALESSANDRO      17        1558          9   
4          MONTE NAPOLEONE       6         219          1   
6              DOMENICHINO       2        6383          7   
7   VIGLIANI PAOLO ONORATO      59        6422          8   
8            DELLE BETULLE      12        6828          7   
9          SANTA RADEGONDA       3         208          1   
10                  PADOVA     111        2275          2   
11        ROSSI PELLEGRINO      33        1510          9   

    Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  
0                    292.0                       NaN                  292.0  
1                    800.0                       NaN                  800.0  
2                    726.0                       NaN                    NaN  
3                    370.0                       NaN                  370.0  
4                    270.0                       NaN                  270.0  
6                    795.0                     622.0                 1417.0  
7                   1225.0                       NaN                 1225.0  
8                    620.0                     766.0                 1386.0  
9                  20340.0                       NaN                20340.0  
10                   400.0                       NaN                 1129.0  
11                  1197.0                       NaN                 1197.0

In [ ]:
DATA['Insegna'].value_counts().head(10)

Insegna
Mancante       348
carrefour       30
esselunga       17
punto sma       13
pam             12
lidl            10
blockbuster      9
oviesse          9
unes             9
upim             9
Name: count, dtype: int64

In [ ]:
#Settore merceologico imputation
popular_supermarket = ['esselunga', 'pam', 'carrefour', 'supermarket', 'punto sma', 'lidl']

def fill_nan(row):
    if pd.isna(row['Settore_merceologico']):
        #check from 'Insegna'
        if row['Insegna'] in popular_supermarket:
            return 'alimentare/non alimentare'
        else:
            #impute as the mode
            return DATA['Settore_merceologico'].mode()[0]
    return row['Settore_merceologico']

# Apply the function to the DataFrame
DATA.loc[:, 'Settore_merceologico'] = DATA.apply(fill_nan, axis=1)

DATA[DATA['Settore_merceologico'].isna()].shape[0]

0

Regarding the 'Superficie...' attributes, we have integrity rules such that the sum of the first two columns must be equal to the third one. Therefore, in rows where only one value is missing out of the three, we can simply compute the missing value as the difference or sum of the other two.


In [ ]:

for index, row in DATA.iterrows():

  # Case 1: Only 'Superficie_vendita' is missing
  if np.isnan(row['Superficie_vendita[m²]']) and not np.isnan(row['Superficie_altri_usi[m²]']) and not np.isnan(row['Superficie_totale[m²]']):
    DATA.loc[index, 'Superficie_vendita[m²]'] = row['Superficie_totale[m²]'] - row['Superficie_altri_usi[m²]']

  # Case 2: Only 'Superficie_altri_usi' is missing
  elif np.isnan(row['Superficie_altri_usi[m²]']) and not np.isnan(row['Superficie_vendita[m²]']) and not np.isnan(row['Superficie_totale[m²]']):
    DATA.loc[index, 'Superficie_altri_usi[m²]'] = row['Superficie_totale[m²]'] - row['Superficie_vendita[m²]']

  # Case 3: Only 'Superficie_totale[m²]' is missing
  elif np.isnan(row['Superficie_totale[m²]']) and not np.isnan(row['Superficie_vendita[m²]']) and not np.isnan(row['Superficie_altri_usi[m²]']):
    DATA.loc[index, 'Superficie_totale[m²]'] = row['Superficie_vendita[m²]'] + row['Superficie_altri_usi[m²]']

  # Case 4: 'Superficie_vendita' and 'Superficie_altri_usi' are missing
  elif np.isnan(row['Superficie_vendita[m²]']) and np.isnan(row['Superficie_altri_usi[m²]']) and not np.isnan(row['Superficie_totale[m²]']):
    DATA.loc[index, 'Superficie_vendita[m²]'] = row['Superficie_totale[m²]']
    DATA.loc[index, 'Superficie_altri_usi[m²]'] = 0

  # Case 5: 'Superficie_totale' and 'Superficie_altri_usi' are missing
  elif not np.isnan(row['Superficie_vendita[m²]']) and np.isnan(row['Superficie_altri_usi[m²]']) and np.isnan(row['Superficie_totale[m²]']):
    DATA.loc[index, 'Superficie_totale[m²]'] = row['Superficie_vendita[m²]']
    DATA.loc[index, 'Superficie_altri_usi[m²]'] = 0

  # Case 6: Only 'Superficie_altri_usi' is non-NaN, drop the row
  elif np.isnan(row['Superficie_vendita[m²]']) and not np.isnan(row['Superficie_altri_usi[m²]']) and np.isnan(row['Superficie_totale[m²]']):
    DATA.drop(index, inplace=True)

  # Case 7: All three values are NaN, drop the row
  elif np.isnan(row['Superficie_vendita[m²]']) and np.isnan(row['Superficie_altri_usi[m²]']) and np.isnan(row['Superficie_totale[m²]']):
    DATA.drop(index, inplace=True)

  else:
    continue


In [ ]:
#Now that all missing values are gone i should check if all rows satisfy the consistency rules, if not correct them
CONSISTENT_ROWS = ((DATA['Superficie_totale[m²]'] > 0) &
                   (DATA['Superficie_vendita[m²]'] > 0) &
                   (DATA['Superficie_altri_usi[m²]'] >= 0) &
                   (DATA['Superficie_totale[m²]'] == (DATA['Superficie_vendita[m²]'] + DATA['Superficie_altri_usi[m²]'])))
DATA[~CONSISTENT_ROWS]
#TODO the remainin one

Settore_merceologico          Insegna Tipo Via  \
19     alimentare/non alimentare         Mancante      PLE   
100    alimentare/non alimentare             coin      CSO   
102    alimentare/non alimentare             coin      PLE   
155    alimentare/non alimentare  gs supermercato      VIA   
172    alimentare/non alimentare       iperstanda      VIA   
227    alimentare/non alimentare        punto sma      PZA   
229    alimentare/non alimentare        punto sma      VIA   
236    alimentare/non alimentare        punto sma      VLE   
570               non alimentare         Mancante      VLE   
903  tabella speciale carburanti         Mancante      VIA   

                 Denominazione  Civico  Codice Via  Municipio  \
19                     FERRARA       2        4158          4   
100                   VERCELLI      30        6193          7   
102                     LORETO      16        2264          2   
155         MAESTRI CAMPIONESI       7        3197          4   
172  TRIVULZIO ANTONIO TOLOMEO      12        6277          7   
227                   BRUZZANO       5        1655          9   
229    BUONARROTI MICHELANGELO      11        6253          7   
236                       PISA      10        6615          7   
570                    GORIZIA      14        5156          6   
903              SANT' ARNALDO      26        1663          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  
19                    536.0                    -482.0                   54.0  
100                  3500.0                    1300.0                 5880.0  
102                  1910.0                    1100.0                 3684.0  
155                  1416.0                      22.0                 2852.0  
172                  3200.0                    2164.0                 5570.0  
227                   380.0                      50.0                 1200.0  
229                   400.0                     450.0                 1030.0  
236                   270.0                     140.0                  691.0  
570                   400.0                     400.0                  402.0  
903                   600.0                     300.0                  600.0

As we saw in the profiling step some lines are inconsistent with the integrity rules over 'Superficie totale'. Three possible solutions:
- Invalidate 'Superficie totale' and recompute it using the other two values.
- Invalidate 'Superficie altri usi' and recompute it using the other two values.
- Invalidate 'Superficie vendita' and recompute it using the other two values.


From the profiling step we saw that the most 'unreliable' attribute was 'Superficie altri usi' hence we chose to invalidate that one and recompute it using the other two.

In [ ]:
if DATA[~CONSISTENT_ROWS].shape[0] != 0:
  for index, row in DATA[~CONSISTENT_ROWS].iterrows():
    DATA.loc[index, 'Superficie_altri_usi[m²]'] = row['Superficie_totale[m²]'] - row['Superficie_vendita[m²]']


In [ ]:
#Check if there's still non consistent tuples
CONSISTENT_ROWS = ((DATA['Superficie_totale[m²]'] > 0) &
                   (DATA['Superficie_vendita[m²]'] > 0) &
                   (DATA['Superficie_altri_usi[m²]'] >= 0) &
                   (DATA['Superficie_totale[m²]'] == (DATA['Superficie_vendita[m²]'] + DATA['Superficie_altri_usi[m²]'])))
DATA[~CONSISTENT_ROWS]

Settore_merceologico   Insegna Tipo Via Denominazione  Civico  \
19  alimentare/non alimentare  Mancante      PLE       FERRARA       2   

    Codice Via  Municipio  Superficie_vendita[m²]  Superficie_altri_usi[m²]  \
19        4158          4                   536.0                    -482.0   

    Superficie_totale[m²]  
19                   54.0

In [ ]:
#There is still one tuple that violates constraints
if DATA[~CONSISTENT_ROWS].shape[0] != 0:
  for index, row in DATA[~CONSISTENT_ROWS].iterrows():
    DATA.loc[index, 'Superficie_altri_usi[m²]'] = 0.0
    DATA.loc[index, 'Superficie_totale[m²]'] = row['Superficie_vendita[m²]']

Now all tuples are consistent wrt consistency rules

### **c.** Data Deduplication

In [ ]:
DATA.duplicated().any()

True

In [ ]:
DATA[DATA.duplicated()]

Settore_merceologico             Insegna Tipo Via         Denominazione  \
360       non alimentare            Mancante      VIA  ALBERICO DA ROSCIATE   
589       non alimentare            Mancante      VLE              SABOTINO   
848       non alimentare  ricordi medi store      CSO          BUENOS AIRES   

     Civico  Codice Via  Municipio  Superficie_vendita[m²]  \
360       5        6589          7                   726.0   
589       4        4046          5                   350.0   
848      33        2129          3                  1190.0   

     Superficie_altri_usi[m²]  Superficie_totale[m²]  
360                       0.0                  726.0  
589                       0.0                  350.0  
848                     553.0                 1743.0

In [ ]:
DATA = DATA.drop_duplicates()
DATA

Settore_merceologico              Insegna Tipo Via  \
0                 non alimentare             Mancante      PZA   
1                 non alimentare             Mancante      RIP   
2                 non alimentare             Mancante      VIA   
3                 non alimentare             Mancante      VIA   
4                 non alimentare             Mancante      VIA   
..                           ...                  ...      ...   
906   tabella speciale monopolio             Mancante      VIA   
907  tabella speciale carburanti             Mancante      VIA   
908    tabella speciale farmacie             farmacia      VIA   
909    tabella speciale farmacie  farmacia cassiodoro      VLE   
910    tabella speciale farmacie     farmacia scevola      VLE   

            Denominazione  Civico  Codice Via  Municipio  \
0                CORDUSIO       2         626          1   
1         DI PTA TICINESE      73        5150          6   
2    ALBERICO DA ROSCIATE       5        6589          7   
3     ASTESANI ALESSANDRO      17        1558          9   
4         MONTE NAPOLEONE       6         219          1   
..                    ...     ...         ...        ...   
906          MACCHI MAURO      42        2133          2   
907             GALLARATE      40        7420          8   
908      MAFFUCCI ANGIOLO      40        1276          9   
909            CASSIODORO      12        6359          8   
910          TESTI FULVIO      90        1441          9   

     Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_totale[m²]  
0                     292.0                       0.0                  292.0  
1                     800.0                       0.0                  800.0  
2                     726.0                       0.0                  726.0  
3                     370.0                       0.0                  370.0  
4                     270.0                       0.0                  270.0  
..                      ...                       ...                    ...  
906                   350.0                     475.0                  825.0  
907                   800.0                     100.0                  900.0  
908                   462.0                     291.0                  753.0  
909                   591.0                     185.0                  776.0  
910                   397.0                     227.0                  624.0  

[904 rows x 10 columns]

In [ ]:
DATA.reset_index(drop=True, inplace=True)
DATA.head(30)

Settore_merceologico               Insegna Tipo Via  \
0              non alimentare              Mancante      PZA   
1              non alimentare              Mancante      RIP   
2              non alimentare              Mancante      VIA   
3              non alimentare              Mancante      VIA   
4              non alimentare              Mancante      VIA   
5   alimentare/non alimentare             esselunga      VIA   
6   alimentare/non alimentare             esselunga      VLE   
7              non alimentare          in s mercato      VIA   
8              non alimentare  la rinascente s.p.a.      VIA   
9   alimentare/non alimentare                   pam      VIA   
10  alimentare/non alimentare           supermarket      VIA   
11                 alimentare              Mancante      PLE   
12                 alimentare              Mancante      VIA   
13                 alimentare          in s mercato      VIA   
14                 alimentare             punto sma      VIA   
15  alimentare/non alimentare              Mancante      CSO   
16  alimentare/non alimentare              Mancante      VIA   
17  alimentare/non alimentare              Mancante      GLL   
18  alimentare/non alimentare              Mancante      PLE   
19  alimentare/non alimentare              Mancante      PLE   
20  alimentare/non alimentare              Mancante      PLE   
21  alimentare/non alimentare              Mancante      PZA   
22  alimentare/non alimentare              Mancante      PZA   
23  alimentare/non alimentare              Mancante      PZA   
24  alimentare/non alimentare              Mancante      CSO   
25  alimentare/non alimentare              Mancante      VIA   
26  alimentare/non alimentare              Mancante      VIA   
27  alimentare/non alimentare              Mancante      VIA   
28  alimentare/non alimentare              Mancante      VIA   
29  alimentare/non alimentare              Mancante      VIA   

               Denominazione  Civico  Codice Via  Municipio  \
0                   CORDUSIO       2         626          1   
1            DI PTA TICINESE      73        5150          6   
2       ALBERICO DA ROSCIATE       5        6589          7   
3        ASTESANI ALESSANDRO      17        1558          9   
4            MONTE NAPOLEONE       6         219          1   
5                DOMENICHINO       2        6383          7   
6     VIGLIANI PAOLO ONORATO      59        6422          8   
7              DELLE BETULLE      12        6828          7   
8            SANTA RADEGONDA       3         208          1   
9                     PADOVA     111        2275          2   
10          ROSSI PELLEGRINO      33        1510          9   
11                 SELINUNTE       2        6566          7   
12                DEI PIATTI       3         532          1   
13                    ROMBON      34        2659          3   
14         MAGGI CARLO MARIA      10        7115          1   
15         MATTEOTTI GIACOMO      14         218          1   
16                     EDOLO      26        1217          2   
17                 DEL CORSO       4         305          1   
18                   FERRARA       2        4158          4   
19                 SELINUNTE       2        6566          7   
20                 SELINUNTE       2        6566          7   
21                 DEL DUOMO      31           1          1   
22         DELLA TRIVULZIANA       6        1765          9   
23             SIGMUND FREUD       1        1705          9   
24                  VERCELLI      20        6193          7   
25  GRASSI GIOVANNI BATTISTA      98        7465          8   
26          ANTONINI GIACOMO      32        4250          5   
27                      ARCO       2         714          1   
28                   BENADIR       5        2380          2   
29             BIANCHI MOSE'      94        6385          7   

    Superficie_vendita[m²]  Superficie_altri_usi[m²]  Superficie_total

In [ ]:

indexer = recordlinkage.index.SortedNeighbourhood(
      on='Denominazione', window=9)

candidate_links = indexer.index(DATA)
candidate_links

MultiIndex([( 13,  10),
            ( 57,  49),
            ( 68,  38),
            ( 72,  22),
            ( 92,   2),
            ( 93,  18),
            (101,  56),
            (104,  25),
            (105,  63),
            (109, 101),
            ...
            (896, 495),
            (897, 112),
            (898,  12),
            (899, 100),
            (899, 283),
            (900, 107),
            (901, 131),
            (902, 115),
            (902, 144),
            (903, 521)],
           length=8173)

In [ ]:
print(DATA.columns)
print(DATA.shape)

Index(['Settore_merceologico', 'Insegna', 'Tipo Via', 'Denominazione',
       'Civico', 'Codice Via', 'Municipio', 'Superficie_vendita[m²]',
       'Superficie_altri_usi[m²]', 'Superficie_totale[m²]'],
      dtype='object')
(904, 10)


In [ ]:
compare_cl = recordlinkage.Compare()


compare_cl.exact('Municipio', 'Municipio', label='Municipio')
compare_cl.exact('Codice Via', 'Codice Via', label='Codice Via')
compare_cl.exact('Civico', 'Civico', label='Civico')
compare_cl.string('Tipo Via', 'Tipo Via', method='jarowinkler', threshold=0.8, label='Tipo Via')
compare_cl.string('Denominazione', 'Denominazione', method='jarowinkler', threshold=0.8, label='Denominazione')

features = compare_cl.compute(candidate_links, DATA)
matches = features[features.sum(axis=1) > 4]

matches

Municipio  Codice Via  Civico  Tipo Via  Denominazione
19  11           1           1       1       1.0            1.0
20  11           1           1       1       1.0            1.0
    19           1           1       1       1.0            1.0
67  24           1           1       1       1.0            1.0
74  16           1           1       1       1.0            1.0
...            ...         ...     ...       ...            ...
892 766          1           1       1       1.0            1.0
893 529          1           1       1       1.0            1.0
895 486          1           1       1       1.0            1.0
901 263          1           1       1       1.0            1.0
903 94           1           1       1       1.0            1.0

[175 rows x 5 columns]

In [ ]:
print(matches.index)
print(' ')

for i in matches.index:
    print(DATA.iloc[[i[0],i[1]]])

MultiIndex([( 19,  11),
            ( 20,  11),
            ( 20,  19),
            ( 67,  24),
            ( 74,  16),
            (140,  35),
            (164,  32),
            (167, 166),
            (176, 127),
            (177, 134),
            ...
            (883, 644),
            (888, 396),
            (890, 455),
            (890, 456),
            (891, 298),
            (892, 766),
            (893, 529),
            (895, 486),
            (901, 263),
            (903,  94)],
           length=175)
 
         Settore_merceologico   Insegna Tipo Via Denominazione  Civico  \
19  alimentare/non alimentare  Mancante      PLE     SELINUNTE       2   
11                 alimentare  Mancante      PLE     SELINUNTE       2   

    Codice Via  Municipio  Superficie_vendita[m²]  Superficie_altri_usi[m²]  \
19        6566          7                   329.0                     424.0   
11        6566          7                   330.0                     423.0   

    Superficie_to

In [ ]:
DATA_DROP_DUPLICATES = DATA.copy()
indexes = []
for i in matches.index:
    if i[1] not in indexes:
        DATA_DROP_DUPLICATES = DATA_DROP_DUPLICATES.drop([i[1]])
    indexes.append(i[1])

In [ ]:
DATA = DATA_DROP_DUPLICATES

In [ ]:
DATA.reset_index(drop=True, inplace=True)

## **3.** Additional quality assestment

In [ ]:
DATA.describe()

Civico   Codice Via   Municipio  Superficie_vendita[m²]  \
count  773.000000   773.000000  773.000000              773.000000   
mean    29.727038  3348.620957    4.276843              761.165589   
std     43.557558  2501.650248    2.869970              993.631076   
min      1.000000     1.000000    1.000000              251.000000   
25%      6.000000  1114.000000    1.000000              350.000000   
50%     15.000000  2554.000000    4.000000              495.000000   
75%     35.000000  5374.000000    7.000000              862.000000   
max    312.000000  7587.000000    9.000000            20340.000000   

       Superficie_altri_usi[m²]  Superficie_totale[m²]  
count                773.000000             773.000000  
mean                 345.614489            1106.780078  
std                  964.809606            1552.383758  
min                    0.000000             251.000000  
25%                    0.000000             392.000000  
50%                   42.000000             600.000000  
75%                  327.000000            1200.000000  
max                17183.000000           20340.000000

In [ ]:
NUM = list(DATA.select_dtypes(include=['int64','float64']).columns)
DATA_NUM = DATA[NUM]
DATA_NUM.corr(method ='pearson')

Civico  Codice Via  Municipio  \
Civico                    1.000000    0.120914   0.147020   
Codice Via                0.120914    1.000000   0.641583   
Municipio                 0.147020    0.641583   1.000000   
Superficie_vendita[m²]    0.038379    0.037540   0.048167   
Superficie_altri_usi[m²]  0.030039    0.128866   0.127320   
Superficie_totale[m²]     0.043235    0.104119   0.109960   

                          Superficie_vendita[m²]  Superficie_altri_usi[m²]  \
Civico                                  0.038379                  0.030039   
Codice Via                              0.037540                  0.128866   
Municipio                               0.048167                  0.127320   
Superficie_vendita[m²]                  1.000000                  0.256469   
Superficie_altri_usi[m²]                0.256469                  1.000000   
Superficie_totale[m²]                   0.799464                  0.785659   

                          Superficie_totale[m²]  
Civico                                 0.043235  
Codice Via                             0.104119  
Municipio                              0.109960  
Superficie_vendita[m²]                 0.799464  
Superficie_altri_usi[m²]               0.785659  
Superficie_totale[m²]                  1.000000

CORRELATIONS CONSIDERATION:
The correlation between Codice Via and Municipio (originally ZD) got a little bit higher after the cleaning

In [ ]:
# functional dependency -> same street address should correspond to always the same ZD and Codice Via
fd_via_zona = DATA.groupby(["Tipo Via", "Denominazione"])["Municipio"].nunique().max() <= 1
print("La combinazione Tipo Via + Denominazione determina univocamente Municipio?", fd_via_zona)
fd_via_cod = DATA.groupby(["Tipo Via", "Denominazione"])["Codice Via"].nunique().max() <= 1
print("La combinazione Tipo Via + Denominazione determina univocamente Codice Via?", fd_via_cod)

La combinazione Tipo Via + Denominazione determina univocamente Municipio? True
La combinazione Tipo Via + Denominazione determina univocamente Codice Via? True


Now also the Functional Dependacy ("Tipo Via", "Denominazione") -> ("Municipio") is respected

We can now perform the same quality assestment of the beginning and compare the results

In [ ]:
for col in DATA.columns:
    print("DQ Assessment for "+col+":")

    DISTINCT = (DATA[col].nunique())
    COUNT = DATA[col].count()
    ROWS = len(DATA[col])
    UNIQUENESS = DISTINCT / ROWS
    print("UNIQUENESS: ", UNIQUENESS)

    DISTINCTNESS = DISTINCT / COUNT
    print("DISTINCTNESS: ", DISTINCTNESS)

    MAX_COUNTS = max(DATA[col].value_counts())
    CONSTANCY = MAX_COUNTS / COUNT
    print("CONSTANCY: ", CONSTANCY)


    NULL = DATA[col].isnull().sum()
    NOT_NULL = ROWS - NULL
    COMPLETENESS = NOT_NULL / ROWS
    print("COMPLETENESS: ", COMPLETENESS)

    print("\n\n")

DQ Assessment for Settore_merceologico:
UNIQUENESS:  0.007761966364812419
DISTINCTNESS:  0.007761966364812419
CONSTANCY:  0.6908150064683053
COMPLETENESS:  1.0



DQ Assessment for Insegna:
UNIQUENESS:  0.4333764553686934
DISTINCTNESS:  0.4333764553686934
CONSTANCY:  0.37257438551099614
COMPLETENESS:  1.0



DQ Assessment for Tipo Via:
UNIQUENESS:  0.016817593790426907
DISTINCTNESS:  0.016817593790426907
CONSTANCY:  0.6520051746442432
COMPLETENESS:  1.0



DQ Assessment for Denominazione:
UNIQUENESS:  0.6351875808538163
DISTINCTNESS:  0.6351875808538163
CONSTANCY:  0.0258732212160414
COMPLETENESS:  1.0



DQ Assessment for Civico:
UNIQUENESS:  0.15782664941785252
DISTINCTNESS:  0.15782664941785252
CONSTANCY:  0.07632600258732213
COMPLETENESS:  1.0



DQ Assessment for Codice Via:
UNIQUENESS:  0.6429495472186287
DISTINCTNESS:  0.6429495472186287
CONSTANCY:  0.02328589909443726
COMPLETENESS:  1.0



DQ Assessment for Municipio:
UNIQUENESS:  0.01164294954721863
DISTINCTNESS:  0.0116429495

In [ ]:
#Let's do it again but considering only the non null rows
CONSISTENT_ROWS = (DATA['Superficie_totale[m²]'] > 0) & (DATA['Superficie_totale[m²]'] == (DATA['Superficie_vendita[m²]'] + DATA['Superficie_altri_usi[m²]']))
print('Consistent rows for Superficie totale (only notna rows): ' + str(CONSISTENT_ROWS.sum()) + ' - ' + str(int(CONSISTENT_ROWS.sum()/DATA.shape[0]*100)) + '%')
print('NON consistent rows:')
DATA[~CONSISTENT_ROWS][['Superficie_vendita[m²]', 'Superficie_altri_usi[m²]', 'Superficie_totale[m²]']]

Consistent rows for Superficie totale (only notna rows): 773 - 100%
NON consistent rows:


Empty DataFrame
Columns: [Superficie_vendita[m²], Superficie_altri_usi[m²], Superficie_totale[m²]]
Index: []

In [ ]:
PROFILE = ProfileReport(DATA)
PROFILE.to_file("PROFILE.html")
PROFILE

Output hidden; open in https://colab.research.google.com to view.

## Cleaned dataset

We removed the underscore used during the cleaning phase that was needed to conform the input to the programming language, now we just clean it

In [ ]:
DATA.rename(columns={'Settore_merceologico': 'Settore merceologico',
                     'Superficie_vendita[m²]': 'Superficie vendita[m²]',
                     'Superficie_altri_usi[m²]' : 'Superficie altri usi[m²]',
                     'Superficie_totale[m²]' : 'Superficie totale[m²]',
                     }, inplace=True)

In [ ]:
DATA

Settore merceologico              Insegna Tipo Via  \
0                 non alimentare             Mancante      PZA   
1                 non alimentare             Mancante      VIA   
2                 non alimentare             Mancante      VIA   
3      alimentare/non alimentare            esselunga      VIA   
4      alimentare/non alimentare            esselunga      VLE   
..                           ...                  ...      ...   
768   tabella speciale monopolio             Mancante      VIA   
769  tabella speciale carburanti             Mancante      VIA   
770    tabella speciale farmacie             farmacia      VIA   
771    tabella speciale farmacie  farmacia cassiodoro      VLE   
772    tabella speciale farmacie     farmacia scevola      VLE   

              Denominazione  Civico  Codice Via  Municipio  \
0                  CORDUSIO       2         626          1   
1      ALBERICO DA ROSCIATE       5        6589          7   
2       ASTESANI ALESSANDRO      17        1558          9   
3               DOMENICHINO       2        6383          7   
4    VIGLIANI PAOLO ONORATO      59        6422          8   
..                      ...     ...         ...        ...   
768            MACCHI MAURO      42        2133          2   
769               GALLARATE      40        7420          8   
770        MAFFUCCI ANGIOLO      40        1276          9   
771              CASSIODORO      12        6359          8   
772            TESTI FULVIO      90        1441          9   

     Superficie vendita[m²]  Superficie altri usi[m²]  Superficie totale[m²]  
0                     292.0                       0.0                  292.0  
1                     726.0                       0.0                  726.0  
2                     370.0                       0.0                  370.0  
3                     795.0                     622.0                 1417.0  
4                    1225.0                       0.0                 1225.0  
..                      ...                       ...                    ...  
768                   350.0                     475.0                  825.0  
769                   800.0                     100.0                  900.0  
770                   462.0                     291.0                  753.0  
771                   591.0                     185.0                  776.0  
772                   397.0                     227.0                  624.0  

[773 rows x 10 columns]

Final CSV of the Clean Dataset

In [ ]:
DATA.to_csv('DATASET_CLEANED.csv', index=False)